### ISSUE TITLE
更改快捷键的的when条件

### ISSUE THREAD

**Issue by heartacker** [KuKuDeCheng/md-color#1]
快捷键应该加入这个条件。仅支持md文件。不然所有语言都会受影响。
`editorLangId == 'markdown'`

**Comment by zhangchengk** [comment]
> 快捷键应该加入这个条件。仅支持md文件。不然所有语言都会受影响。
> `editorLangId == 'markdown'`

已经修改了 并且还限定是  选择文本的条件，右键菜单增加了可指定的 红色 绿色 橘色的选项

**Comment by heartacker** [comment]
😢 哈哈.谢谢你.但是本来我的右键菜单就很多了.结果现在更多了.
![image](https://user-images.githubusercontent.com/1876302/107225201-7b655380-6a53-11eb-9d50-04d703a4dcd2.png)
这个右键菜单可以取消吧.

**Comment by zhangchengk** [comment]
> 😢 哈哈.谢谢你.但是本来我的右键菜单就很多了.结果现在更多了.
> ![image](https://user-images.githubusercontent.com/1876302/107225201-7b655380-6a53-11eb-9d50-04d703a4dcd2.png)
> 这个右键菜单可以取消吧.
哈哈  我也是右键md菜单有点多  就晒选了3个(red green orange)，本来想挂个二级菜单的，但是在vscode官网上没有找到相关的API
